// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyiJbSvKDwCToaxhj9BOlHN248jrqE76I',
    appId: '1:483799839585:web:d355dd7e000a67ff638b20',
    messagingSenderId: '483799839585',
    projectId: 'corsit-app-2025',
    authDomain: 'corsit-app-2025.firebaseapp.com',
    storageBucket: 'corsit-app-2025.firebasestorage.app',
    measurementId: 'G-YYFBYWCGBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI6fvCQOXz_u7Yz8OJdr8XpOyXz5p84wo',
    appId: '1:483799839585:android:fc7cbd1eb789c6cc638b20',
    messagingSenderId: '483799839585',
    projectId: 'corsit-app-2025',
    storageBucket: 'corsit-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Sh8m8I0ipUsPY76takxKmIVQIzsqxHw',
    appId: '1:483799839585:ios:786deff122a5863d638b20',
    messagingSenderId: '483799839585',
    projectId: 'corsit-app-2025',
    storageBucket: 'corsit-app-2025.firebasestorage.app',
    iosClientId:
        '483799839585-g2q2dbkuhgli4mkfmhbh87jtvgd5ghjs.apps.googleusercontent.com',
    iosBundleId: 'com.corsit.club.corsit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Sh8m8I0ipUsPY76takxKmIVQIzsqxHw',
    appId: '1:483799839585:ios:786deff122a5863d638b20',
    messagingSenderId: '483799839585',
    projectId: 'corsit-app-2025',
    storageBucket: 'corsit-app-2025.firebasestorage.app',
    iosClientId:
        '483799839585-g2q2dbkuhgli4mkfmhbh87jtvgd5ghjs.apps.googleusercontent.com',
    iosBundleId: 'com.corsit.club.corsit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyiJbSvKDwCToaxhj9BOlHN248jrqE76I',
    appId: '1:483799839585:web:f5ee00a129a32b57638b20',
    messagingSenderId: '483799839585',
    projectId: 'corsit-app-2025',
    authDomain: 'corsit-app-2025.firebaseapp.com',
    storageBucket: 'corsit-app-2025.firebasestorage.app',
    measurementId: 'G-JS4ZCQ12V7',
  );
}
